# Site settings
title: Welcome to panda's Home
email: panda2gogo@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  ....
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://panda2go.github.io" # the base hostname & protocol for your site
twitter_username: @Panda2go2Panda
github_username:  panda2go

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
job.title: "IT Cloud Engineer"
excerpt_separator: "<!--more-->"

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""
