# Site settings
# Site settings
author: panda
title: Welcome to panda's Home
email: panda2gogo@gmail.com
description: Check out http://turtle2go.github.io for more information on new technology 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://panda2go.github.io" # the base hostname & protocol for your site

# Footer에 넣을 소셜아이콘들을 위해 설정
twitter_username: turtle2go
github_username:  turtle2go
facebook_username: turtle2go
linkedin_username: in/changmo-kim-a99b6b14a
telegram_username: turtle2go


# Build settings
markdown: kramdown
encoding: "utf-8"
# Other options
permalink: blog/:year/:month/:title
job.title: "IT Cloud Engineer"
excerpt_separator: "<!--more-->"

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""
